### ISSUE TITLE
baidu网盘下载Synthetic Chinese String Dataset 解压有问题

### ISSUE THREAD

**Issue by am9x** [YCG09/chinese_ocr#10]
显示
Unexpected end of archive
----------- ---------  ---------- -----  ----
            796352447                    322723

一共才能认出322723个文件

**Comment by am9x** [comment]
mac 百度客户端下载了两遍，
mac linux win 都试过解压一样的问题

**Comment by YCG09** [comment]
@am9x 那你试试caffe_ocr作者提供的原数据吧，我只是搬运了一下，本不应该有问题，https://pan.baidu.com/s/1dFda6R3#list/path=%2F

**Comment by am9x** [comment]
谢谢，我再用win下载一遍看看
