### ISSUE TITLE
Request clarity on Densetnet traning

### ISSUE THREAD

**Issue by srijiths** [YCG09/chinese_ocr#104]
Hi @YCG09 

Its a nice project. Would like to get one clarity on Densenet training part. In data_train.txt and data_test.txt you have the image and its co-ordinates not the labels. For text recognition task you need image and label right ?

And i see in your train.py you are taking data_train and data_test text files. I assume Denset is been used for text recognition part right ? Then ideally it requires image and label pair as in SynthText. 

Would be grateful if you clarify this.

Thank You

**Comment by Julyliying** [comment]
Hi, @srijiths 
In data_train.txt and data_test.txt, the numbers are not co-ordinates, they are  labels. One  number corresponds to one class of the dictionary,and that is label.

**Comment by srijiths** [comment]
Thank you @Julyliying for the clarification.
