### ISSUE TITLE
prepare_training_data/split_label.py

### ISSUE THREAD

**Issue by fire717** [YCG09/chinese_ocr#105]
split_label.py中对应的path和gt_path分别对应图片和标签的链接哈，但是图片和标签分别是什么格式呢？
比如图片，就是一张张放在path目录下哈，那标签呢？是一个单个的txt或者json或者其他什么，还是对应图片单个的文件，其中每个文件格式又如何呢
谢谢

**Comment by fire717** [comment]
自己研究代码看出来了。。标注文件为txt与图片一一对应。txt内部为八个数值，对应四个角点坐标。
供后来人参考。

**Comment by Julyliying** [comment]
txt内部是10个数值。。。。  数字对应的不是坐标，是样本图片上的文字在字典中对应的类别

**Comment by fire717** [comment]
你可能跟我说的不是一个东西..我说的是我们自己的数据 标注的txt格式，然后再去调用split_label,而且我自己跑完没有问题。
你可以看看split_label.py的源代码
`splitted_line = line.strip().lower().split(',')
        pt_x = np.zeros((4, 1))
        pt_y = np.zeros((4, 1))
        pt_x[0, 0] = int(float(splitted_line[0]) / img_size[1] * re_size[1])
        pt_y[0, 0] = int(float(splitted_line[1]) / img_size[0] * re_size[0])
        pt_x[1, 0] = int(float(splitted_line[2]) / img_size[1] * re_size[1])
        pt_y[1, 0] = int(float(splitted_line[3]) / img_size[0] * re_size[0])
        pt_x[2, 0] = int(float(splitted_line[4]) / img_size[1] * re_size[1])
        pt_y[2, 0] = int(float(splitted_line[5]) / img_size[0] * re_size[0])
        pt_x[3, 0] = int(float(splitted_line[6]) / img_size[1] * re_size[1])
        pt_y[3, 0] = int(float(splitted_line[7]) / img_size[0] * re_size[0])
`
你认为这个不是坐标嘛

**Comment by YCG09** [comment]
@fire717 你们说的不是一回事，你说的没问题，他说的是训练识别模型用的txt

**Comment by fire717** [comment]
嗯嗯 了解 谢谢两位哈

**Comment by nuaaxiaoyi** [comment]
想再问一下，这个txt文件每一行4个坐标数值是怎么得到的？x1,y1,x2,y2,x3,y3,x4,y4,这些数值是不是用哪个文件生成的？
