### ISSUE TITLE
data_train.txt的生成方式

### ISSUE THREAD

**Issue by LiangHao92** [YCG09/chinese_ocr#11]
请问楼主，训练中所需要的data_train.txt是怎样生成的，应该是每个字对应在字典中的序号是么，有生成脚本么

**Comment by YCG09** [comment]
图片对应的文本是样本生成的时候产出的，然后将每个字符转化为字典中的index位置

**Comment by LiangHao92** [comment]
@YCG09 好的，谢谢。还想请问一下，你在densenet中定义的nclass为5000，这个nclass是对应识别的字符数量么，字典中的字符数量不是5990么
