### ISSUE TITLE
Exception when training with SynthText data

### ISSUE THREAD

**Issue by srijiths** [YCG09/chinese_ocr#117]
Hi All,

I have tried training SynthText data and i observe that after some epochs its getting in to below exception. 

tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at ctc_loss_op.cc:168 : Invalid argument: All labels must be nonnegative integers, batch: 94 labels: -1
Traceback (most recent call last):
  File "train.py", line 181, in <module>
    callbacks = [checkpoint, earlystop, changelr, tensorboard])
  File "/home/ubuntu/srijith/dl/lib/python3.5/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/srijith/dl/lib/python3.5/site-packages/keras/engine/training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/ubuntu/srijith/dl/lib/python3.5/site-packages/keras/engine/training_generator.py", line 217, in fit_generator
    class_weight=class_weight)
  File "/home/ubuntu/srijith/dl/lib/python3.5/site-packages/keras/engine/training.py", line 1217, in train_on_batch
    outputs = self.train_function(ins)
  File "/home/ubuntu/srijith/dl/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)
  File "/home/ubuntu/srijith/dl/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)
  File "/home/ubuntu/srijith/dl/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1439, in __call__
    run_metadata_ptr)
  File "/home/ubuntu/srijith/dl/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: All labels must be nonnegative integers, batch: 94 labels: -1
         [[{{node ctc/CTCLoss}} = CTCLoss[_class=["loc:@training/Adam/gradients/ctc/CTCLoss_grad/mul"], ctc_merge_repeated=true, ignore_longer_outputs_than_inputs=false, preprocess_collapse_repeated=false, _device="/job:localhost/replica:0/task:0/device:CPU:0"](ctc/Log, ctc/ToInt64, ctc/ToInt32_2, ctc/ToInt32_1)]]

Thank You,
Srijith

**Comment by srijiths** [comment]
Its happening even if i put a try except in gen function with in while loop. I have printed the label size , and its coming as BATCH_SIZE. What would be the issue ?

Thank You

**Comment by srijiths** [comment]
lbl size : 128
  404/56000 [..............................] - ETA: 114:13:30 - loss: -0.1496 - acc: 0.0106lbl size : 128 128
  758/56000 [..............................] - ETA: 106:24:35 - loss: -0.3673 - acc: 0.0057lbl size : 128
2018-11-15 10:59:14.739383: W tensorflow/core/framework/op_kernel.cc:1341] OP_REQUIRES failed at ctc_loss_op.cc:168 : Invalid argument: All labels must be nonnegative integers, batch: 81 labels: -1
Traceback (most recent call last):
  File "train.py", line 169, in <module>
    callbacks = [checkpoint, earlystop, changelr, tensorboard])
  File "/home/ubuntu/srijith/dl/lib/python3.5/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/srijith/dl/lib/python3.5/site-packages/keras/engine/training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/ubuntu/srijith/dl/lib/python3.5/site-packages/keras/engine/training_generator.py", line 217, in fit_generator
    class_weight=class_weight)
  File "/home/ubuntu/srijith/dl/lib/python3.5/site-packages/keras/engine/training.py", line 1217, in train_on_batch
    outputs = self.train_function(ins)
  File "/home/ubuntu/srijith/dl/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)
  File "/home/ubuntu/srijith/dl/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)
  File "/home/ubuntu/srijith/dl/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1439, in __call__
    run_metadata_ptr)
  File "/home/ubuntu/srijith/dl/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: All labels must be nonnegative integers, batch: 81 labels: -1
         [[{{node ctc/CTCLoss}}]]

**Comment by YCG09** [comment]
Invalid argument: All labels must be nonnegative integers, batch: 81 labels: -1

**Comment by srijiths** [comment]
Issue due to improper images in SynthText dataset.

**Comment by srijiths** [comment]
There are two issues with data. Publishing this to help the ones who are trying with VGG SynthText Dataset.

Below listed are the improper images in SynthText dataset. You need to remove below listed images from each file mentioned.

annotation_train.txt
./images/2069/4/192_whittier_86389.jpg
./images/2025/2/364_SNORTERS_72304.jpg
./images/2356/5/370_Definable_20054.jpg
./images/2194/2/334_EFFLORESCENT_24742.jpg
./images/1817/2/363_actuating_904.jpg
./images/2013/2/370_refract_63890.jpg
./images/1881/4/225_Marbling_46673.jpg
./images/2128/2/369_REDACTED_63458.jpg
./images/1863/4/223_Diligently_21672.jpg
./images/1730/2/361_HEREON_35880.jpg
./images/1650/2/355_stony_74902.jpg
./images/1332/4/224_TETHERED_78397.jpg
./images/1696/4/211_Queened_61779.jpg
./images/936/2/375_LOCALITIES_44992.jpg
./images/869/4/234_TRIASSIC_80582.jpg
./images/913/4/231_randoms_62372.jpg
./images/905/4/234_Postscripts_59142.jpg
./images/596/2/372_Ump_81662.jpg
./images/264/2/362_FORETASTE_30276.jpg
./images/384/4/220_bolts_8596.jpg
./images/627/6/83_PATRIARCHATE_55931.jpg
./images/368/4/232_friar_30876.jpg
./images/495/6/81_MIDYEAR_48332.jpg
./images/429/4/208_Mainmasts_46140.jpg
./images/554/2/366_Teleconferences_77948.jpg
./images/173/2/358_BURROWING_10395.jpg
./images/275/6/96_hackle_34465.jpg

annotation_val.txt
./images/2557/2/351_DOWN_23492.jpg
./images/2489/4/221_snored_72290.jpg
./images/2540/4/246_SQUAMOUS_73902.jpg

annotation_test.txt

./images/2852/6/60_TOILSOME_79481.jpg
./images/2911/6/77_heretical_35885.jpg
./images/2749/6/101_Chided_13155.jpg

Second problem is max char length. SynthText has around 1.2 million images having max char lenght greater than 10 ( which is max char len in this repo ). So in the readfile method you need to filter all images where its label > 10.

**Comment by tjpulfn** [comment]
hello @srijiths 
I am not use the VGG SynthText Dataset to train , the train datasets of my project is random generation with a dict. So what the improper images have any common features?

**Comment by srijiths** [comment]
I might not be able to tell you whats happening with your dataset. First
you write simple script juat to read all images and throw an exception if
there is any read error. This will bring corrupted images if there is any.

Pls post the error which u r getting.

**Comment by tjpulfn** [comment]
Hi, Thank you very much ,i  solved the issue.

**Comment by jamesguo** [comment]
> Hi, Thank you very much ,i solved the issue.

你怎么解决的呢

**Comment by xuewenyuan** [comment]
> There are two issues with data. Publishing this to help the ones who are trying with VGG SynthText Dataset.
> 
> Below listed are the improper images in SynthText dataset. You need to remove below listed images from each file mentioned.
> 
> annotation_train.txt
> ./images/2069/4/192_whittier_86389.jpg
> ./images/2025/2/364_SNORTERS_72304.jpg
> ./images/2356/5/370_Definable_20054.jpg
> ./images/2194/2/334_EFFLORESCENT_24742.jpg
> ./images/1817/2/363_actuating_904.jpg
> ./images/2013/2/370_refract_63890.jpg
> ./images/1881/4/225_Marbling_46673.jpg
> ./images/2128/2/369_REDACTED_63458.jpg
> ./images/1863/4/223_Diligently_21672.jpg
> ./images/1730/2/361_HEREON_35880.jpg
> ./images/1650/2/355_stony_74902.jpg
> ./images/1332/4/224_TETHERED_78397.jpg
> ./images/1696/4/211_Queened_61779.jpg
> ./images/936/2/375_LOCALITIES_44992.jpg
> ./images/869/4/234_TRIASSIC_80582.jpg
> ./images/913/4/231_randoms_62372.jpg
> ./images/905/4/234_Postscripts_59142.jpg
> ./images/596/2/372_Ump_81662.jpg
> ./images/264/2/362_FORETASTE_30276.jpg
> ./images/384/4/220_bolts_8596.jpg
> ./images/627/6/83_PATRIARCHATE_55931.jpg
> ./images/368/4/232_friar_30876.jpg
> ./images/495/6/81_MIDYEAR_48332.jpg
> ./images/429/4/208_Mainmasts_46140.jpg
> ./images/554/2/366_Teleconferences_77948.jpg
> ./images/173/2/358_BURROWING_10395.jpg
> ./images/275/6/96_hackle_34465.jpg
> 
> annotation_val.txt
> ./images/2557/2/351_DOWN_23492.jpg
> ./images/2489/4/221_snored_72290.jpg
> ./images/2540/4/246_SQUAMOUS_73902.jpg
> 
> annotation_test.txt
> 
> ./images/2852/6/60_TOILSOME_79481.jpg
> ./images/2911/6/77_heretical_35885.jpg
> ./images/2749/6/101_Chided_13155.jpg
> 
> Second problem is max char length. SynthText has around 1.2 million images having max char lenght greater than 10 ( which is max char len in this repo ). So in the readfile method you need to filter all images where its label > 10.

This list saves me a lot time. Thank you!

**Comment by Papaass** [comment]
Hello @srijiths ,
 Can i have the link to dowload the SynthText data please ?

Best regards
