### ISSUE TITLE
请问怎么识别出空格

### ISSUE THREAD

**Issue by pustar** [YCG09/chinese_ocr#14]
目前空格识别不出来，比如识别出的英文单词间没有空格，前后直接粘连到一起，有什么办法可以解决这个问题吗？

**Comment by YCG09** [comment]
这需要在样本中加入一些带空格的来训练

**Comment by jewelcai** [comment]
> 目前空格识别不出来，比如识别出的英文单词间没有空格，前后直接粘连到一起，有什么办法可以解决这个问题吗？

请问应该怎么做空格识别呢？  多谢了

**Comment by YCG09** [comment]
@jewelcai 加入一些带空格的的样本训练模型，能识别出一些
