### ISSUE TITLE
训练时间

### ISSUE THREAD

**Issue by Qsongl** [YCG09/chinese_ocr#140]
请问大家的训练时间多久啊，我的显示怎么这么久
![image](https://user-images.githubusercontent.com/41495766/50077084-592e6d00-021e-11e9-81ca-a0ac3f689d10.png)

**Comment by xxlxx1** [comment]
@Qsongl  平均是400ms/step 你这很奇怪，是不是cpu进程太多了？或者没用GPU

**Comment by Qsongl** [comment]
@xxlxx1 用的就是gpu哇，您训练的时间是多久的呢

**Comment by xxlxx1** [comment]
@Qsongl 图片大小不同batch size不同时间也不同，但是一般就是400ms/step 左右

**Comment by Qsongl** [comment]
@xxlxx1 我用的就是github上的数据集呀，图片大小，batch size都没改。。。一轮需要100多个小时。。。

**Comment by mayidu** [comment]
您好！麻烦问一下，你的这个训练时间的问题最后是如何解决的呢，我现在也遇到了这样的问题 @YCG09 @xxlxx1

**Comment by Qsongl** [comment]
我这个是因为没有用到gpu，因为服务器的gpu环境是在root下的，当时没有用到gpu😂 😂

**Comment by Lanme** [comment]
我用的是两块GPU，改了batch_size=512，一个epoch大概五小时，我还以为我已经很慢了...

**Comment by fzy0728** [comment]
请问使用了gpu后一次需要多久？我这边很奇怪，使用gpu需要30h/epoch，显存占满了，但是GPU使用率为0.

**Comment by fzy0728** [comment]
> 我这个是因为没有用到gpu，因为服务器的gpu环境是在root下的，当时没有用到gpu😂 😂

请问使用了gpu后一次需要多久？我这边很奇怪，使用gpu需要30h/epoch，显存占满了，但是GPU使用率为0.
