### ISSUE TITLE
有人尝试在Windows上部署识别部分么？

### ISSUE THREAD

**Issue by AlanNewImage** [YCG09/chinese_ocr#144]
我尝试使用opencv的dnn模块加载freeze后的pb模型，dnn不支持permute(2,1,3)。

**Comment by AlanNewImage** [comment]
另外，在win上部署识别有哪些前向框架推荐么？感谢

**Comment by AlanNewImage** [comment]
最终是用tensorflow

**Comment by Sammul40619** [comment]
@AlanNewImage 你好，我最近也打算在win上部署这个模型，尝试了opencv导入模型，确实有这个permute这个问题，把这个问题fix后，又遇到了新的问题，说某个层找不到input_layer。请问你用的tensorflow，是用的tensorflow C++接口吗？

**Comment by AlanNewImage** [comment]
> @AlanNewImage 你好，我最近也打算在win上部署这个模型，尝试了opencv导入模型，确实有这个permute这个问题，把这个问题fix后，又遇到了新的问题，说某个层找不到input_layer。请问你用的tensorflow，是用的tensorflow C++接口吗？

是的。源码编译的tf c++
