### ISSUE TITLE
运行sh文件出错

### ISSUE THREAD

**Issue by onedoge** [YCG09/chinese_ocr#17]
AttributeError: 'MSVCCompiler' object has no attribute 'compiler_so
![1](https://user-images.githubusercontent.com/21003563/39567756-9583ab06-4ef2-11e8-804f-924c346c866c.png)

**Comment by onedoge** [comment]
请问有遇到这样的错误吗？如何解决？谢谢

**Comment by YCG09** [comment]
你这是Windows吧...

**Comment by piaobuliao** [comment]
可以参考 https://github.com/eragonruan/text-detection-ctpn/issues/73 
在windows下cpu模式是可以的 我刚弄好

**Comment by 18813055625** [comment]
@piaobuliao 
能说一下改了哪些地方吗？
