### ISSUE TITLE
使用自己制作的图片训练,报了这个错误

### ISSUE THREAD

**Issue by 928234269** [YCG09/chinese_ocr#186]
![image](https://user-images.githubusercontent.com/40171666/54423975-da799b00-474c-11e9-9034-3f977bc2ad55.png)

**Comment by 928234269** [comment]
我在densenet训练时使用了不固定长度的图片,报了这个错,我该怎么样改呢

**Comment by chiminghui** [comment]
这个是输入图片尺寸与网络输入要求不一致导致的，需要把你的输入图片resize到（280,32）

**Comment by YCG09** [comment]
训练的时候图片长度必须固定
