### ISSUE TITLE
训练的问题

### ISSUE THREAD

**Issue by LiangHao92** [YCG09/chinese_ocr#19]
楼主你好，请问你是直接就用这个代码对数据进行训练的么，我用自己的数据训练后效果感觉不如你的。因为用了自己的数据，我把字典进行了更改，字符都是8个字符的数据，改了maxlength，请问还需要改什么地方么

**Comment by YCG09** [comment]
8个字符的话，图片宽度可以缩小一点

**Comment by qiangqiangsir** [comment]
弱弱的问一句，楼主这个训练怎么没有生产checkpoint，我训练了两天了，才发现没有checkpoint

**Comment by YCG09** [comment]
@qiangqiangsir 参考#18
