### ISSUE TITLE
CTPN detect  行间距小的情况下 存在漏检的情况

### ISSUE THREAD

**Issue by jewelcai** [YCG09/chinese_ocr#194]
CTPN detect  行间距小的情况下 存在漏检的情况
请问是不是得改善数据集  重新训练模型来改善？
![tmp_trained](https://user-images.githubusercontent.com/8166517/54900486-6ab69d80-4f0e-11e9-9d0d-fc48d8edc62c.png)

**Comment by jewelcai** [comment]
增加box个数

**Comment by jjl001** [comment]
在哪里增加啊？

**Comment by luoyan1113** [comment]
同问在哪增加box的个数
