### ISSUE TITLE
请问一下报 已放弃(吐核) 什么意思呢?

### ISSUE THREAD

**Issue by 79534505** [YCG09/chinese_ocr#2]
`
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
已放弃(吐核)
`

**Comment by YCG09** [comment]
是执行setup.sh时报的错吗？

**Comment by YCG09** [comment]
cpu环境需要修改下setup.sh，把for gpu部分注释掉，把for cpu部分解开注释

**Comment by KyrieHee** [comment]
batch_size改小一些。
