### ISSUE TITLE
识别空格

### ISSUE THREAD

**Issue by jewelcai** [YCG09/chinese_ocr#200]
作者您好，
我发现5990个字符里已经有了空格这个label，是不是只需要在训练样本里加上包含空格的数据来训练，就可以识别空格了？

**Comment by YCG09** [comment]
是的

**Comment by jake221** [comment]
> 是的

感谢作者，关于空格，我有个问题请教如下。按照现在图片的编码和char_std_5990.txt的对应关系，如果出现空格，则编码为0，但是在后面train.py中会出现0-1=-1的情况。

**Comment by jewelcai** [comment]
> > 是的
> 
> 感谢作者，关于空格，我有个问题请教如下。按照现在图片的编码和char_std_5990.txt的对应关系，如果出现空格，则编码为0，但是在后面train.py中会出现0-1=-1的情况。
> 
> labels[i, :len(str)] = [int(k)-1 for k in str]

把-1去了

**Comment by jake221** [comment]
> > > 是的
> > 
> > 
> > 感谢作者，关于空格，我有个问题请教如下。按照现在图片的编码和char_std_5990.txt的对应关系，如果出现空格，则编码为0，但是在后面train.py中会出现0-1=-1的情况。
> > labels[i, :len(str)] = [int(k)-1 for k in str]
> 
> 把-1去了

嗯我是去了解决这个问题的，但是还是有点疑惑，我感觉作者在char_std_5990.txt的第一行不是空格，而是一个换行符，例如在train.py里面打印char_set和它的size是不包含空格的，因此我在自己的字典中添加了一行放空格。

，的。一是0不在有、人“”了中国大为1:上2这个以年生和我时之也来到要会学对业出行公能他于5e3而发地....卍 
5990

不知道有何不妥。

加下你微信如何？我的wechat 15651859966

**Comment by jewelcai** [comment]
> > > > 是的
> > > 
> > > 
> > > 感谢作者，关于空格，我有个问题请教如下。按照现在图片的编码和char_std_5990.txt的对应关系，如果出现空格，则编码为0，但是在后面train.py中会出现0-1=-1的情况。
> > > labels[i, :len(str)] = [int(k)-1 for k in str]
> > 
> > 
> > 把-1去了
> 
> 嗯我是去了解决这个问题的，但是还是有点疑惑，我感觉作者在char_std_5990.txt的第一行不是空格，而是一个换行符，例如在train.py里面打印char_set和它的size是不包含空格的，因此我在自己的字典中添加了一行放空格。
> 
> ，的。一是0不在有、人“”了中国大为1:上2这个以年生和我时之也来到要会学对业出行公能他于5e3而发地....卍
> 5990
> 
> 不知道有何不妥。
> 
> 加下你微信如何？我的wechat 15651859966

我没用那个txt文件，直接用key.py

**Comment by jake221** [comment]
> > > > > 是的
> > > > 
> > > > 
> > > > 感谢作者，关于空格，我有个问题请教如下。按照现在图片的编码和char_std_5990.txt的对应关系，如果出现空格，则编码为0，但是在后面train.py中会出现0-1=-1的情况。
> > > > labels[i, :len(str)] = [int(k)-1 for k in str]
> > > 
> > > 
> > > 把-1去了
> > 
> > 
> > 嗯我是去了解决这个问题的，但是还是有点疑惑，我感觉作者在char_std_5990.txt的第一行不是空格，而是一个换行符，例如在train.py里面打印char_set和它的size是不包含空格的，因此我在自己的字典中添加了一行放空格。
> > ，的。一是0不在有、人“”了中国大为1:上2这个以年生和我时之也来到要会学对业出行公能他于5e3而发地....卍
> > 5990
> > 不知道有何不妥。
> > 加下你微信如何？我的wechat 15651859966
> 
> 我没用那个txt文件，直接用key.py

你说的是推理态，训练时候还是要用到char_std_5990的，除非你改了代码

**Comment by jewelcai** [comment]
> > > > > > 是的
> > > > > 
> > > > > 
> > > > > 感谢作者，关于空格，我有个问题请教如下。按照现在图片的编码和char_std_5990.txt的对应关系，如果出现空格，则编码为0，但是在后面train.py中会出现0-1=-1的情况。
> > > > > labels[i, :len(str)] = [int(k)-1 for k in str]
> > > > 
> > > > 
> > > > 把-1去了
> > > 
> > > 
> > > 嗯我是去了解决这个问题的，但是还是有点疑惑，我感觉作者在char_std_5990.txt的第一行不是空格，而是一个换行符，例如在train.py里面打印char_set和它的size是不包含空格的，因此我在自己的字典中添加了一行放空格。
> > > ，的。一是0不在有、人“”了中国大为1:上2这个以年生和我时之也来到要会学对业出行公能他于5e3而发地....卍
> > > 5990
> > > 不知道有何不妥。
> > > 加下你微信如何？我的wechat 15651859966
> > 
> > 
> > 我没用那个txt文件，直接用key.py
> 
> 你说的是推理态，训练时候还是要用到char_std_5990的，除非你改了代码

对
