### ISSUE TITLE
请问直接将图片数据集放到images文件夹中就能训练吗？需不需要标注，如果需要标注的话，那txt文件是如何生成的呢？谢谢！

### ISSUE THREAD

**Issue by JJoohhnnn** [YCG09/chinese_ocr#201]
请问直接将图片数据集放到images文件夹中就能训练吗？需不需要标注，如果需要标注的话，那txt文件是如何生成的呢？谢谢！

**Comment by WYanNuo** [comment]
需要标注 data_train.txt data_test.txt 是标注文件 标注文件生成参考https://github.com/Sanster/text_renderer 或者作者给的其他两个链接

**Comment by JJoohhnnn** [comment]
> 需要标注 data_train.txt data_test.txt 是标注文件 标注文件生成参考https://github.com/Sanster/text_renderer 或者作者给的其他两个链接

你好，最后给出的生成自己的样本的链接只是说如何产生图片集，没说怎么生成 .txt的文件啊？

**Comment by YCG09** [comment]
txt是生成样本图片的同时生成的，完事儿会保存下来

**Comment by ericosmic** [comment]
@YCG09  @JJoohhnnn  我试了densenet训练说明中的两个数据生成的程序，但是都没有生成指向字典索引的txt文件，请问这个该怎么办

**Comment by cellphonef** [comment]
> txt是生成样本图片的同时生成的，完事儿会保存下来

你好，我train后生成的h5文件 加载失败 报错 shape不一致
