### ISSUE TITLE
用自己训练好的模型运行时报错？大神帮忙看一下

### ISSUE THREAD

**Issue by JJoohhnnn** [YCG09/chinese_ocr#207]
ValueError: Dimension 1 in both shapes must be equal, but are 5988 and 5987 for 'Assign_159' (op: 'Assign') with input shapes: [768,5988], [768,5987]
算上最开始的空格，我的char_std_5990.txt 一共5987个字符，请问该怎么改啊？

**Comment by PeterBishop0** [comment]
我也遇到这个问题了，求大佬解答一下

**Comment by JJoohhnnn** [comment]
> 我也遇到这个问题了，求大佬解答一下

我感觉是nclass不对

**Comment by PeterBishop0** [comment]
@JJoohhnnn 好像可以自己改字符，你现在训练成功了吗

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by JJoohhnnn** [comment]
没有成功，我觉得作者的train.py训练出的模型网络结构是不是变了，预训练模型也加载不进去




------------------ 原始邮件 ------------------
发件人: "PeterBishop"<notifications@github.com>; 
发送时间: 2019年4月27日(星期六) 中午12:50
收件人: "YCG09/chinese_ocr"<chinese_ocr@noreply.github.com>; 
抄送: "John"<1767013330@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [YCG09/chinese_ocr] 用自己训练好的模型运行时报错？大神帮忙看一下 (#207)




@JJoohhnnn 好像可以自己改字符，你现在训练成功了吗
 
Sent with GitHawk

**Comment by YCG09** [comment]
检查一下你data_train.txt里的字符编号是否在0-5986范围内
