### ISSUE TITLE
训练集合只能定长吗？

### ISSUE THREAD

**Issue by tw2016xjtu** [YCG09/chinese_ocr#22]
您好，我目前在您这份代码的基础上改动后在训练一个集合，对您这个模型感觉很棒。但我现在想知道能否改变训练集合的长度，能否让训练集的长度任意？或者是改变长度？，但是我们训练的时候希望，希望您能百忙之中抽出时间为我解答。

**Comment by YCG09** [comment]
CTC的输入需要是固定长度，train.py里定义了maxlabellength，实际label长度不要超过这个就行

**Comment by tw2016xjtu** [comment]
如果长度超出这个值的图片样本，会影响识别效果吗？

**Comment by YCG09** [comment]
超出会报错，labels初始化的时候限定了maxlabellength尺寸
labels = np.ones([batchsize, maxlabellength])
