### ISSUE TITLE
关于训练的数据集疑问

### ISSUE THREAD

**Issue by cvnli** [YCG09/chinese_ocr#221]
根据作者提供的网盘下载数据集，有一个360万数据集可以用于训练densenet的识别模型，另外一个100万的彩色图像数据集是干什么用的，有谁知道吗？

**Comment by WYanNuo** [comment]
好像没有什么用 作者还没处理过的 没有用到的数据集

**Comment by cvnli** [comment]
> 好像没有什么用 作者还没处理过的 没有用到的数据集

谢谢

**Comment by TyrionChou** [comment]
这360万的数据有标注文件吗？

**Comment by llf10811020205** [comment]
@TyrionChou  找到标注文件了? 能分享吗?

**Comment by TyrionChou** [comment]
> @TyrionChou 找到标注文件了? 能分享吗?

之前找到了，但没有保存，你去找一下issue里面

**Comment by llf10811020205** [comment]
谢谢
