### ISSUE TITLE
请教一下如何使用pb模型进行测试？

### ISSUE THREAD

**Issue by zwy4896** [YCG09/chinese_ocr#229]
从生成的权重文件转到了pb，想测试一下pb模型，但不知道如何去做，请高手指点

**Comment by an1018** [comment]
@zwy4896 你好，你这个问题解决了吗？应该如何测试呢

**Comment by an1018** [comment]
已解决，导入模型，设置feed_dict即可

**Comment by cuimiao187561** [comment]
你好，我现在识别模型h5转pb,但是测试结果和h5结果不一样，@@zwy4896
