### ISSUE TITLE
能否修改数据字典

### ISSUE THREAD

**Issue by flycocopig** [YCG09/chinese_ocr#23]
我在数据字典中删除了些字符然后又加了些生僻字字符，然后在此字典上生成训练样本建模得出模型后去识别，完全识别不正确。

**Comment by flycocopig** [comment]
我想问是不是不能修改数据字典啊

**Comment by flycocopig** [comment]
模型训练的时候一直都在收敛，但是拿去使用的时候同一张图片每次识别输出的结果都不一样。假如识别不正确但每次输出的字符都一样的话还好，请问作者或者是哪位大神能帮忙解惑下

**Comment by flycocopig** [comment]
模型训练的时候一直都在收敛，但是拿去使用的时候同一张图片每次识别输出的结果都不一样。假如识别不正确但每次输出的字符都一样的话还好，请问作者或者是哪位大神能帮忙解惑下

**Comment by ericosmic** [comment]
@YCG09    我是修改字典替换了5个原有的字符，保持字典长度为5990， 因为只想提高这几个新加入字符的识别率，所以只对模型进行fine-tune，只训练模型最后5层， 但是得出的val-acc停留在0.3左右，有办法提高吗
