### ISSUE TITLE
如何生成densenet训练使用的data-train.txt

### ISSUE THREAD

**Issue by ericosmic** [YCG09/chinese_ocr#232]
@YCG09 @JJoohhnnn 我试了densenet训练说明中的两个数据生成的程序，但是都没有生成指向字典索引的txt文件，请问这个该怎么办

**Comment by JJoohhnnn** [comment]
改一下程序 里面有参数设置

**Comment by ericosmic** [comment]
> 改一下程序 里面有参数设置 可以生成txt
使用TextRecognitionDataGenerator是没有生成txt标注文件的，
而使用text_renderer程序可以生成txt文件，但是其中标注都是中文结果，而不是字典索引，你说的改动是在这个程序里吗

**Comment by jake221** [comment]
> > 改一下程序 里面有参数设置 可以生成txt
> 
> 使用TextRecognitionDataGenerator是没有生成txt标注文件的，
> 而使用text_renderer程序可以生成txt文件，但是其中标注都是中文结果，而不是字典索引，你说的改动是在这个程序里吗

TextRecognitionDataGenerator有生成txt标注文件的功能，请看参数-na
