### ISSUE TITLE
请问楼主制作样本的时候都用了哪些字体

### ISSUE THREAD

**Issue by flycocopig** [YCG09/chinese_ocr#24]
我自己制作样本生成的模型测试的时候识别不出来，但是用工程自带的模型能识别，只是准确率不高。后来发现是字体问题，所以想咨询下楼主都使用了哪些字体？

**Comment by YCG09** [comment]
项目里的训练样本是caffe_ocr作者给的，我自己生成样本用的字体基本都是一些常用的，宋体、楷体、黑体等
