### ISSUE TITLE
关于训练后模型不能用问题

### ISSUE THREAD

**Issue by cellphonef** [YCG09/chinese_ocr#244]
我用46*120进行训练得到的h5文件 在model加载时 报错
ValueError: Dimension 0 in both shapes must be equal, but are 768 and 960. Shapes are [768,5990] and [960,5990]. for 'Assign_159' (op: 'Assign') with input shapes: [768,5990], [960,5990].

怎么解决啊 @YCG09

**Comment by fsfwl11406** [comment]
我也遇到了这个问题，请问你解决了吗，谢谢

**Comment by jewelcai** [comment]
训练得到的inputshape得和你predict的时候一致

**Comment by cellphonef** [comment]
> 我也遇到了这个问题，请问你解决了吗，谢谢

我resize了 训练的图片也要和之前的图片一样

**Comment by cellphonef** [comment]
resize到和作者一样的大小 32*280把 不resize的方法我也不会
