### ISSUE TITLE
识别出现部分文本框最后一个字识别不到的问题

### ISSUE THREAD

**Issue by pingzi5233** [YCG09/chinese_ocr#253]
不知大家是否遇到过，文本框的最后一个字识别不到的问题，直接没有识别结果，检测出来的文本框是很好的，很清楚，但就是会出现这个问题，而且并不是所有的都会出现此类问题，想知道是否是我参数哪里设置的不对吗？

**Comment by Maruidear** [comment]
请问你的问题解决了吗？

**Comment by pingzi5233** [comment]
没有呢，因为是部分会出现此情况，其实有些文本框的前面中段都会出现字识别为空的情况，所以我想还是模型没有训练到位的原因



神玥互联网-科技研究院 王萍
联系电话：13672218501
电子邮箱：wangping@atwasoft.net
 
发件人： Maruidear
发送时间： 2019-07-08 11:11
收件人： YCG09/chinese_ocr
抄送： pingzi5233; Author
主题： Re: [YCG09/chinese_ocr] 识别出现部分文本框最后一个字识别不到的问题 (#253)
请问你的问题解决了吗？

**Comment by pingzi5233** [comment]
没有呢，因为是部分会出现此情况，其实有些文本框的前面中段都会出现字识别为空的情况，所以我想还是模型没有训练到位的原因
