### ISSUE TITLE
关于ctpn和densenet之间数据传递的疑问

### ISSUE THREAD

**Issue by iblackholmes** [YCG09/chinese_ocr#26]
楼主，我十分好奇图片经过ctpn再传入densenet里面的是个什么东西？还是一张图片吗？这个图片和原图有什么区别？

**Comment by YCG09** [comment]
看README.md

**Comment by 18398639574** [comment]
> 传入densenet的是从原图裁剪出来的目标文本框，数量不定

那请问是传入的文本框的坐标位置吗？

**Comment by YCG09** [comment]
@18398639574 对，是的
