### ISSUE TITLE
demo

### ISSUE THREAD

**Issue by ecetang** [YCG09/chinese_ocr#29]
请问微调您的模型后，跑新模型，相同的输入，每次重新跑输出结果都不同，这是为什么

**Comment by YCG09** [comment]
信息有点少，不好确定问题

**Comment by ecetang** [comment]
最后发现是到导入模型的路径出问题。
现在用自己生成的数据重新训练，char_dict增加到6000多个，总共19w训练数据，10个epochs，loss一直在降，但是acc和val_acc一直为0或者非常小，这样正常吗？

**Comment by YCG09** [comment]
不正常，loss能降到多少

**Comment by ecetang** [comment]
loss 20多，acc是e-4/-5

**Comment by YCG09** [comment]
@ecetang 那就还没收敛，loss应该能到0.2左右，再多训练看看，调调lr

**Comment by ecetang** [comment]
谢谢！还有一个问题，load之前保存的模型继续训练，为什么loss和acc像是没load weights时一样。

**Comment by YCG09** [comment]
不应该，pretrain模型的路径写对没

**Comment by ecetang** [comment]
现在不增加字库数量，直接用您的模型继续训练就还比较正常。
请问densenet.py中dense_cnn(input, 5000)，5000是否应该与字库大小对应，我看您不是写5990。
增大字库之后，除了修改char_std_5990.txt，还需要修改什么吗？

**Comment by 1034490826** [comment]
@YCG09 新扩充了字符集，追加了30个中文和标点，一定要重新训练模型吗？可以只训练少部分数据集么（包含新追加字符）
