### ISSUE TITLE
准确率很高,但损失率比较大

### ISSUE THREAD

**Issue by lijc210** [YCG09/chinese_ocr#30]
Epoch 25/30
267/267 [=======] - 91s 340ms/step - loss: 0.0931 - acc: 0.9965 - val_loss: 0.3158 - val_acc: 0.9878
Epoch 26/30
267/267 [[=======] - 91s 339ms/step - loss: 0.1212 - acc: 0.9946 - val_loss: 0.2125 - val_acc: 0.9844
Epoch 27/30
267/267 [[=======] - 91s 340ms/step - loss: 0.0894 - acc: 0.9964 - val_loss: 0.3993 - val_acc: 0.9878
Epoch 28/30
267/267 [[=======] - 91s 340ms/step - loss: 0.1295 - acc: 0.9952 - val_loss: 0.5801 - val_acc: 0.9826

用自己的数据训练时，如上，准确率很高，但损失率比较大，请问楼主这是什么原因，怎么样调整

**Comment by springtty** [comment]
> Epoch 25/30
> 267/267 [=======] - 91s 340ms/step - loss: 0.0931 - acc: 0.9965 - val_loss: 0.3158 - val_acc: 0.9878
> Epoch 26/30
> 267/267 [[=======] - 91s 339ms/step - loss: 0.1212 - acc: 0.9946 - val_loss: 0.2125 - val_acc: 0.9844
> Epoch 27/30
> 267/267 [[=======] - 91s 340ms/step - loss: 0.0894 - acc: 0.9964 - val_loss: 0.3993 - val_acc: 0.9878
> Epoch 28/30
> 267/267 [[=======] - 91s 340ms/step - loss: 0.1295 - acc: 0.9952 - val_loss: 0.5801 - val_acc: 0.9826
> 
> 用自己的数据训练时，如上，准确率很高，但损失率比较大，请问楼主这是什么原因，怎么样调整

兄弟，你的计算速度真快，用的什么配置？数据集有没有改过？

**Comment by xiaosi2017** [comment]
数据集小了吧，才三万张

**Comment by springtty** [comment]
准确率高，损失率大，应该是还不够拟合，数据量确实太小了。

**Comment by xiaosi2017** [comment]
我用的260w张内容相似的，都是一个领域的文本做的图片训得，试了从头训，和用作者的h5
文件做，acc 0.99多  loss  0.4-0.5左右，识别效果都不如作者的，不知为何

**Comment by springtty** [comment]
> 我用的260w张内容相似的，都是一个领域的文本做的图片训得，试了从头训，和用作者的h5
> 文件做，acc 0.99多 loss 0.4-0.5左右，识别效果都不如作者的，不知为何

你迭代了多少次？

**Comment by xiaosi2017** [comment]
> > 我用的260w张内容相似的，都是一个领域的文本做的图片训得，试了从头训，和用作者的h5
> > 文件做，acc 0.99多 loss 0.4-0.5左右，识别效果都不如作者的，不知为何
> 
> 你迭代了多少次？

10个epoch

**Comment by lijc210** [comment]
> > Epoch 25/30
> > 267/267 [=======] - 91s 340ms/step - loss: 0.0931 - acc: 0.9965 - val_loss: 0.3158 - val_acc: 0.9878
> > Epoch 26/30
> > 267/267 [[=======] - 91s 339ms/step - loss: 0.1212 - acc: 0.9946 - val_loss: 0.2125 - val_acc: 0.9844
> > Epoch 27/30
> > 267/267 [[=======] - 91s 340ms/step - loss: 0.0894 - acc: 0.9964 - val_loss: 0.3993 - val_acc: 0.9878
> > Epoch 28/30
> > 267/267 [[=======] - 91s 340ms/step - loss: 0.1295 - acc: 0.9952 - val_loss: 0.5801 - val_acc: 0.9826
> > 用自己的数据训练时，如上，准确率很高，但损失率比较大，请问楼主这是什么原因，怎么样调整
> 
> 兄弟，你的计算速度真快，用的什么配置？数据集有没有改过？

配置是4块NVIDIA Titan X，公司的服务器。
