### ISSUE TITLE
tensorflow与keras的兼容问题

### ISSUE THREAD

**Issue by unstory** [YCG09/chinese_ocr#300]
最新版本的keras会调用以下语句：
from tensorflow.python.eager import context

但是tensorflow1.3.0没有eager模块，会报
ModuleNotFoundError: No module named 'tensorflow.python.eager

最新的keras版本与tensorflow1.3.0不兼容，安装keras时需要指定版本,
keras与tensorflow的版本对应表：
https://docs.floydhub.com/guides/environments/

**Comment by BeenLi** [comment]
Have a good day~
