### ISSUE TITLE
什么时候能把生成识别样本的代码共享下

### ISSUE THREAD

**Issue by flycocopig** [YCG09/chinese_ocr#31]
感谢作者提供了这么优秀的OCR项目，但是我在用自己生成的样本去训练模型一直都达不到想要的效果，语料库、字体、背景图都试过还是不太好还不如使用作者原本模型的效果。虽然觉得很无理但还是想问问楼主能否提供下生成样本的工程看看

**Comment by xxllp** [comment]
@flycocopig  你最好把作者也要了吧，这种数据涉及隐私吧

**Comment by shenxiao2019** [comment]
同求!
