### ISSUE TITLE
results

### ISSUE THREAD

**Issue by qwertyuiop194** [YCG09/chinese_ocr#323]
执行demo.py
results中每个图像对应的txt中的数字代表什么

**Comment by kaiyiuw** [comment]
如果你是指, e.g. 
img_0001.jpg 12 34 55 899 21 99 90 81 778 800
當中的數字是每個字的代號，e.g. 如沒記錯，29 代表"我" 字

**Comment by qwertyuiop194** [comment]
Thanks for your answer.
那英文或数字呢，每一个字母或数字是一个编号吗？
例如：0: [array([1279,   23, 1488,   22, 1280,   70, 1488,   68]), u'42.88D']

**Comment by kaiyiuw** [comment]
英文或数字，我也這做的，例如： 1=A, 2=B, ...., 26=Z
不過不確定對不對的。

而這array 中的數列，應該是, scale up 過的box coordinates.

**Comment by qwertyuiop194** [comment]
ok, thank you.
