### ISSUE TITLE
cannot import name 'bbox'

### ISSUE THREAD

**Issue by Ludasheng** [YCG09/chinese_ocr#340]
from . import bbox
ImportError: cannot import name 'bbox' from 'ctpn.lib.utils'

**Comment by Ludasheng** [comment]
> ```
> from . import bbox
> ```
> 
> ImportError: cannot import name 'bbox' from 'ctpn.lib.utils'

**Comment by nguyengiaphuc1992** [comment]
please let me know solution ?
