### ISSUE TITLE
运行demo.py，第一次耗时较长，达到一百多秒，而且识别效果不佳。。这个是为什么？

### ISSUE THREAD

**Issue by lmw0320** [YCG09/chinese_ocr#365]
我都是加载的博主提供的模型文件，然后进行检测，发现耗时较长，第一张用时183秒，而且识别效果很差（检测效果倒还可以）。。
![1](https://user-images.githubusercontent.com/37755235/91165719-bc66e700-e703-11ea-9679-84eab9326d3f.png)
![2](https://user-images.githubusercontent.com/37755235/91165810-eb7d5880-e703-11ea-8761-e0e6af4c2a80.png)

后面第2张的检测也很耗时，我也查看了GPU，占用很满啊。。8G显存难道不够么？？

**Comment by alan-img** [comment]
怎么解决的，我也遇到了同样的问题
