### ISSUE TITLE
无法加载VGG模型

### ISSUE THREAD

**Issue by Jiangshuyi0V0** [YCG09/chinese_ocr#369]
在进行ctpn训练时，无法加载作者提供的VGG_imagenet模型，运行train_net.py时会抛出相关异常
![OI7SENS2WTIWGNYFXLM9YHE](https://user-images.githubusercontent.com/55131005/101283425-359ecb80-3815-11eb-9ba4-3894568c9c79.png)

错误部分的对应代码为
![image](https://user-images.githubusercontent.com/55131005/101283444-61ba4c80-3815-11eb-95ec-a5a173cebbf9.png)

如图为下载并放置好的VGG模型
![image](https://user-images.githubusercontent.com/55131005/101283469-88788300-3815-11eb-9530-0f601bae9edf.png)

求问各位大佬们为啥会出现这种问题，本科在读萌新真诚发问，可以直接留言或者加Q:2754194439救我，感激不尽！

**Comment by knavezl** [comment]
numpy降级，pip install numpy==1.16.2
