### ISSUE TITLE
运行demo,a结果是一堆乱码

### ISSUE THREAD

**Issue by oldliyoungli** [YCG09/chinese_ocr#37]
我想请教下：
运用您已经提供的模型，我自己保存的模型运行出来是别的都是乱码，是怎么回事呢？
万分感谢！

**Comment by YCG09** [comment]
参考这个吧 #27

**Comment by RobinHan24** [comment]
这个乱码问题，很可能是环境配置不对，所有的配置都用anaconda来，看是否还会出现。
