### ISSUE TITLE
训练数据格式

### ISSUE THREAD

**Issue by zxy3416391** [YCG09/chinese_ocr#4]
你好，请问训练样本data_train.txt，标签只能是对应字符集里面的数字吗，可以直接改成中文吗？比如说：“001.jpg 湖边南路”这种。因为我看到实在decode阶段才把label找到对应char_std的文字，所以具体要在哪里进行更改呢

**Comment by YCG09** [comment]
那样得训练时候去找label中每个字的index位置，不如直接先找好吧
