### ISSUE TITLE
具体代码问题

### ISSUE THREAD

**Issue by sjf18** [YCG09/chinese_ocr#41]
大神你好，请问在准备数据时那个gen函数里labels = np.ones([batchsize, maxlabellength]) * 10000这个乘以10000是什么意思啊，还有input_length[i] = imagesize[1] // 8这里为什么要整除8呢，谢谢！

**Comment by Hugh0120** [comment]
同问10000

**Comment by YCG09** [comment]
10000是用来初始化矩阵的，取比字符个数大的值就行，避免和字符集里的字符编号冲突
