### ISSUE TITLE
训练好的模型，测试的输出结果是空

### ISSUE THREAD

**Issue by focuswuke** [YCG09/chinese_ocr#43]
我在楼主的训练集基础上添加了10万张训练集，对应的标签也都添加了。训练结果如下：
Epoch 7/10
773/773 [==============================] - 9231s 12s/step - loss: 0.8825 - acc: 0.9929 - val_loss: 0.8609 - val_acc: 0.9933
Epoch 00007: early stopping

我将训练好的Epoch 7对应的模型移到路径：chinese_ocr/densenet/models/weights_densenet.h5下，然后进行测试，发现输出结果是空，试了好几张照片都是空。是什么原因呢？

**Comment by YCG09** [comment]
需要用新模型覆盖原来的模型文件

**Comment by focuswuke** [comment]
用训练好的模型weights-densenet-07-0.86.h5，复制到chinese_ocr/densenet/models/下，并修改为：weights_densenet.h5覆盖原文件的，这样操作是对的吗？

**Comment by YCG09** [comment]
对
