### ISSUE TITLE
modelPath = './models/pretrain_model/keras.h5'

### ISSUE THREAD

**Issue by focuswuke** [YCG09/chinese_ocr#44]
在train.py中，modelPath = './models/pretrain_model/keras.h5'这句主要是什么作用？
我在./models/pretrain_model中没看到keras.h5文件

**Comment by YCG09** [comment]
是用来加载预训练的模型的

**Comment by focuswuke** [comment]
在我训练的过程中，在./models/pretrain_model中没看到keras.h5文件，也没有加载预训练的模型，是不是不对啊？
初学者，非常感谢作者的回答~

**Comment by YCG09** [comment]
你可以把训练好的模型放到pretrain_model目录下，可以在下次训练时加载这个模型

**Comment by focuswuke** [comment]
好的~感谢

**Comment by banbsyip** [comment]
> 你可以把训练好的模型放到pretrain_model目录下，可以在下次训练时加载这个模型

请问一下，我训练识别数字时，也是没有看到那个.h5文件，训练的时候没有这个.h5文件，不能运行，但是现在不知道用哪个keras.h5模型文件
