### ISSUE TITLE
训练时出现的问题

### ISSUE THREAD

**Issue by Mango233** [YCG09/chinese_ocr#48]
我运行train.py时,出现
File "train.py", line 113, in gen
    labels[i,:len(str)] =[int(i) - 1 for i in str]
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
我查看了字符类型都是int型,想请问一下该问题如何解决?谢谢

**Comment by YCG09** [comment]
训练部分没有做py2兼容性测试，用py3不会出错

**Comment by Mango233** [comment]
谢谢!
我通过加int(),在py2解决了问题,但还出现了越界的问题
python IndexError: index 350 is out of bounds for axis 0 with size 128
问题出现在
labels[i, :len(str)] =[int(i) - 1 for i in str]
其中 for 内的 i 重命名了,我修改了变量名解决了问题

**Comment by YCG09** [comment]
这样啊，我修正一下
