### ISSUE TITLE
训练不定宽的图片

### ISSUE THREAD

**Issue by hhk123** [YCG09/chinese_ocr#50]
训练样本都是32*280的图片，请问我可以训练不定宽的图片吗？因为自己的样本label的长度不同，resize后又容易失真。

**Comment by YCG09** [comment]
可以，对图片做padding

**Comment by hhk123** [comment]
@YCG09 非常感谢，能跑起来了！

**Comment by focuswuke** [comment]
你好~在做padding的时候，是在哪一步做的处理呢？可以训练任意宽的图片，变成32还是固定的是吗？

**Comment by YCG09** [comment]
@focuswuke 都可以，可以先把图片预处理好，也可以训练时候做

**Comment by Hugh0120** [comment]
可以考虑半角字符转全角

**Comment by wenston2006** [comment]
有个问题想请教下，训练图片里面的样本已经经历了拉伸，旋转等形变；如果训练标签不定长，即便resize到32*280，发生了形变，对训练结果会有很大影响吗？

**Comment by cuimiao187561** [comment]
请问你是在训练不定宽的图片如何加padding@hhk123

**Comment by hhk123** [comment]
在图片读成矩阵之后,用边缘padding.
img = np.pad(img, pad_width=((0, 0), (0, img_std_size[1]-img.shape[1]),(0,0)), mode='edge')
@cuimiao187561

**Comment by cuimiao187561** [comment]
你好，你是在每个batc中所有图像是同一个尺寸吗？例如：batch1 padding到1280*32，batch2 padding 到1440*32吗？你可以吧padding代码发到我的邮箱吗?(1906910382@qq.com),非常感谢你
  

 

 ------------------&nbsp;原始邮件&nbsp;------------------
  发件人:&nbsp;"hhk123"<notifications@github.com&gt;;
 发送时间:&nbsp;2019年10月21日(星期一) 下午5:59
 收件人:&nbsp;"YCG09/chinese_ocr"<chinese_ocr@noreply.github.com&gt;;
 抄送:&nbsp;"shakey"<1906910382@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
 主题:&nbsp;Re: [YCG09/chinese_ocr] 训练不定宽的图片 (#50)

 

 
在图片读成矩阵之后,用边缘padding.
img = np.pad(img, pad_width=((0, 0), (0, img_std_size[1]-img.shape[1]),(0,0)), mode='edge')
@cuimiao187561

**Comment by wenston2006** [comment]
你好,  我后来都padding到统一的尺寸了, 比如48*384; 短的图片padding到384, 长的图片直接缩放到384; 你的1280*32和1440*32给我感觉文本有点长, 训练时lstm会不会产生梯度消失的问题?



在 2019-10-23 10:05:51，"cuimiao187561" <notifications@github.com> 写道：
你好，你是在每个batc中所有图像是同一个尺寸吗？例如：batch1 padding到1280*32，batch2 padding 到1440*32吗？你可以吧padding代码发到我的邮箱吗?(1906910382@qq.com),非常感谢你




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"hhk123"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月21日(星期一) 下午5:59
收件人:&nbsp;"YCG09/chinese_ocr"<chinese_ocr@noreply.github.com&gt;;
抄送:&nbsp;"shakey"<1906910382@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [YCG09/chinese_ocr] 训练不定宽的图片 (#50)




在图片读成矩阵之后,用边缘padding.
img = np.pad(img, pad_width=((0, 0), (0, img_std_size[1]-img.shape[1]),(0,0)), mode='edge')
@cuimiao187561

**Comment by cuimiao187561** [comment]
大佬其实我把lstm去掉了，我直接resNET+ctc,我导师目前在做长文本识别，W比较大




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"wenston2006"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月23日(星期三) 中午11:31
收件人:&nbsp;"YCG09/chinese_ocr"<chinese_ocr@noreply.github.com&gt;;
抄送:&nbsp;"shakey"<1906910382@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [YCG09/chinese_ocr] 训练不定宽的图片 (#50)



你好,  我后来都padding到统一的尺寸了, 比如48*384; 短的图片padding到384, 长的图片直接缩放到384; 你的1280*32和1440*32给我感觉文本有点长, 训练时lstm会不会产生梯度消失的问题?
 
 
 
 在 2019-10-23 10:05:51，"cuimiao187561" <notifications@github.com&gt; 写道：
 你好，你是在每个batc中所有图像是同一个尺寸吗？例如：batch1 padding到1280*32，batch2 padding 到1440*32吗？你可以吧padding代码发到我的邮箱吗?(1906910382@qq.com),非常感谢你
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------
 发件人:&amp;nbsp;"hhk123"<notifications@github.com&amp;gt;;
 发送时间:&amp;nbsp;2019年10月21日(星期一) 下午5:59
 收件人:&amp;nbsp;"YCG09/chinese_ocr"<chinese_ocr@noreply.github.com&amp;gt;;
 抄送:&amp;nbsp;"shakey"<1906910382@qq.com&amp;gt;;"Mention"<mention@noreply.github.com&amp;gt;;
 主题:&amp;nbsp;Re: [YCG09/chinese_ocr] 训练不定宽的图片 (#50)
 
 
 
 
 在图片读成矩阵之后,用边缘padding.
 img = np.pad(img, pad_width=((0, 0), (0, img_std_size[1]-img.shape[1]),(0,0)), mode='edge')
 @cuimiao187561

**Comment by cuimiao187561** [comment]
ocr检测做的还可以，目前中文识别做的不是太好，尤其长文本倾斜识别效果不好
  

 

 ------------------&nbsp;原始邮件&nbsp;------------------
  发件人:&nbsp;"wenston2006"<notifications@github.com&gt;;
 发送时间:&nbsp;2019年10月23日(星期三) 中午11:31
 收件人:&nbsp;"YCG09/chinese_ocr"<chinese_ocr@noreply.github.com&gt;;
 抄送:&nbsp;"shakey"<1906910382@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
 主题:&nbsp;Re: [YCG09/chinese_ocr] 训练不定宽的图片 (#50)

 

你好, 我后来都padding到统一的尺寸了, 比如48*384; 短的图片padding到384, 长的图片直接缩放到384; 你的1280*32和1440*32给我感觉文本有点长, 训练时lstm会不会产生梯度消失的问题?



在 2019-10-23 10:05:51，"cuimiao187561" <notifications@github.com&gt; 写道：
你好，你是在每个batc中所有图像是同一个尺寸吗？例如：batch1 padding到1280*32，batch2 padding 到1440*32吗？你可以吧padding代码发到我的邮箱吗?(1906910382@qq.com),非常感谢你




------------------&amp;nbsp;原始邮件&amp;nbsp;------------------
发件人:&amp;nbsp;"hhk123"<notifications@github.com&amp;gt;;
发送时间:&amp;nbsp;2019年10月21日(星期一) 下午5:59
收件人:&amp;nbsp;"YCG09/chinese_ocr"<chinese_ocr@noreply.github.com&amp;gt;;
抄送:&amp;nbsp;"shakey"<1906910382@qq.com&amp;gt;;"Mention"<mention@noreply.github.com&amp;gt;;
主题:&amp;nbsp;Re: [YCG09/chinese_ocr] 训练不定宽的图片 (#50)




在图片读成矩阵之后,用边缘padding.
img = np.pad(img, pad_width=((0, 0), (0, img_std_size[1]-img.shape[1]),(0,0)), mode='edge')
@cuimiao187561
