### ISSUE TITLE
训练问题

### ISSUE THREAD

**Issue by ladyshen** [YCG09/chinese_ocr#56]
您好，想了解一下对训练数据的要求，除了图片大小为32×280外是否有别的要求？
比如
图片lable不等于10，可以是任意长度吗，如果是任意长度需要修改代码吗？
图像中字体是必须要占满整张图片吗，可以左右上下有空隙吗？

**Comment by ladyshen** [comment]
已验证，解决～

**Comment by wenston2006** [comment]
你好，请问验证结果能否分享一下？
