### ISSUE TITLE
请教一下，在跑完demo后提示内存泄漏是什么原因呢

### ISSUE THREAD

**Issue by tmaccao** [YCG09/chinese_ocr#6]
如下所示，在terminal里输出了识别结果后，会跟两句内存泄漏的提示

512324198106272975
公民身份号码
swig/python detected a memory leak of type 'int64_t *', no destructor found.
swig/python detected a memory leak of type 'int64_t *', no destructor found.

**Comment by YCG09** [comment]
好像是tensorflow1.3的问题，这几个warning有时候有有时候没有
https://github.com/tensorflow/tensorflow/issues/13359

**Comment by tmaccao** [comment]
感谢作者这么快回复，进去链接看了一下，意思是说更高版本的tensorflow里这个问题得到了解决？

**Comment by YCG09** [comment]
恩，应该是的，后面可以尝试升级tf版本看看
