### ISSUE TITLE
为什么对对新闻标题识别正确率很低

### ISSUE THREAD

**Issue by hqsam** [YCG09/chinese_ocr#63]
您好， 就是我直接拿训练好的模型去测试 发现对新闻标题识别正确率很低，只有30多一点 有什么解决方法呢?    然后我用生成数据和加上一些真实新闻数据去训练，测试还行， 但是放在真实图上就有问题了

**Comment by YCG09** [comment]
可能跟字体有关，可以考虑用加粗的字体造些样本
