### ISSUE TITLE
替换CTC端口

### ISSUE THREAD

**Issue by cloudfool** [YCG09/chinese_ocr#66]
有没有试过用基于attention的seq2seq类似的方法来替换CTC？CTC目前依然是比较主流的方法么？

**Comment by Jiakui** [comment]
各有优缺点吧~~~   数据集比较小的情况下，用 ctc 应该更好一点。。。。

**Comment by YCG09** [comment]
attention我试过效果没有ctc好，可能是我打开方式不对
