### ISSUE TITLE
识别一张图片大概要花8秒钟，请问这跟没有使用gpu有关系吗

### ISSUE THREAD

**Issue by MRCHEN3303** [YCG09/chinese_ocr#67]
识别一张图片大概要花8秒钟，请问这跟没有使用gpu有关系吗

**Comment by YCG09** [comment]
有关系，cpu跑ctpn慢很多

**Comment by bing1zhi2** [comment]
@YCG09 @MRCHEN3303 你们好，请教个问题，＃198 。现在我跑不了测试，不管是自己训练的还是预训练的模型，加载模型后报有节点没初始化，请问遇到过没？

**Comment by bing1zhi2** [comment]
#198
