### ISSUE TITLE
请问CTPN

### ISSUE THREAD

**Issue by zhuanjiao2222** [YCG09/chinese_ocr#70]

**Comment by zhuanjiao2222** [comment]
请问这里的CTPN代码是不是没有实现原文章中的side refinement？

**Comment by YCG09** [comment]
是的，没有side refinement部分

**Comment by zhuanjiao2222** [comment]
好的，谢谢

**Comment by jewelcai** [comment]
没有这个 side-refinement 是不是会影响 box 的开始和结束位置？  会不会有截断？

**Comment by YCG09** [comment]
@jewelcai 加入side-refinement框的范围肯定会更精确一些
