### ISSUE TITLE
训练出现问题

### ISSUE THREAD

**Issue by zxy3416391** [YCG09/chinese_ocr#8]
Not enough time for target transition sequence (required: 38, available: 35)58You can turn this error into a warning by using the flag ignore_longer_outputs_than_inputs

不知道是不是因为数据集的原因，我的数据集是不定字长的，然后resize成了280*32，然后运行train.py的时候出错了。

**Comment by zxy3416391** [comment]
[[Node: ctc/CTCLoss = CTCLoss[ctc_merge_repeated=true, ignore_longer_outputs_than_inputs=false, preprocess_collapse_repeated=false, _device="/job:localhost/replica:0/task:0/cpu:0"](ctc/Log/_3121, ctc/ToInt64/_3123, ctc/ToInt32_2/_3125, ctc/ToInt32_1/_3127)]]
         [[Node: training/Adam/gradients/ctc/CTCLoss_grad/mul/_3154 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_5064_training/Adam/gradients/ctc/CTCLoss_grad/mul", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

**Comment by zhangsn828** [comment]
@zxy3416391 你的问题解决了吗？
 [[Node: ctc/CTCLoss = CTCLoss[ctc_merge_repeated=true, ignore_longer_outputs_than_inputs=false, preprocess_collapse_repeated=false, _device="/job:localhost/replica:0/task:0/device:CPU:0"](ctc/Log/_2415, ctc/ToInt64/_2417, ctc/ToInt32_2/_2419, ctc/ToInt32_1/_2421)]]
         [[Node: training/Adam/gradients/ctc/ExpandDims_grad/Shape/_2447 = _HostRecv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_5075_training/Adam/gradients/ctc/ExpandDims_grad/Shape", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]
我这报这个错误是怎么回事呢？

**Comment by YCG09** [comment]
@zxy3416391 indices[449] = [36,35] is out of bounds: need 0 <= index < [128,35]，你训练集里出现了长度为36的sample，检查一下吧

**Comment by YanzheZhangleon** [comment]
@zxy3416391 @YCG09 我也是出现了同样的问题，我的最大标签长度是50。同样提示的是超出了35。我看到35是280//8得到的。不知道是不是这样，但是不知道怎么解决。

**Comment by YCG09** [comment]
@YanzheZhangleon @zxy3416391 你们的训练样本图片宽度是不是不是固定280的

**Comment by zxsheng** [comment]
@YCG09 对于训练数据图片大小不一致该如何去处理比较合适呢？而且最大标签长度也在50左右，强行resize出现的问题也跟上面两位的一致。

**Comment by YanzheZhangleon** [comment]
@zxy3416391 @YCG09 我将标签长度大于35的训练样本全部去掉，图片也直接resize。就不会出现这个问题了。
