### ISSUE TITLE
关于数据集的问题

### ISSUE THREAD

**Issue by loralyc** [YCG09/chinese_ocr#83]
你好，我想问下关于数据集的几个问题。
请问下这个数据集怎么只有图片而没有标签，还是说标签数据在另一个地方下载吗？
还有一个问题是这个庞大的数据集似乎在我的本机解压或服务器上打开查看图片特别卡，卡了一天都打不开文件夹，请问下是有其它合适的软件查看吗？

**Comment by YCG09** [comment]
1、标签在两个txt文件里
2、在txt里有每个图片的文件名，可以cp几张图片到其他目录，再打开查看

**Comment by loralyc** [comment]
你好，能不能解释一下标签代表的意思，我看一个图片后面只对应10个数字，好似没有关于识别方面的标注，谢谢

> 1、标签在两个txt文件里
> 2、在txt里有每个图片的文件名，可以cp几张图片到其他目录，再打开查看

**Comment by loralyc** [comment]
你好，能不能解释一下标签代表的意思，我看一个图片后面只对应10个数字，好似没有关于识别方面的标注，谢谢 @YCG09

**Comment by YCG09** [comment]
数字代表字符编号，即每个字在dictionary里的index位置

**Comment by loralyc** [comment]
好的 非常感谢 @YCG09

**Comment by 18398639574** [comment]
请问dictionary在哪里呢？谢谢！！

**Comment by loralyc** [comment]
@18398639574  train文件夹里有一个txt，如果要改成自己的数据集的话 densenet文件夹里的keys.py也要考虑一下

**Comment by 18398639574** [comment]
但是我没有看到有dictionary呢？谢谢回答~~您能发给我一份吗？18398639574@163.com

**Comment by 18398639574** [comment]
小姐姐or小哥哥，我还想问一下：就是densenet的输入是CTPN对图片截取的文本行结果对吧？那densenet+CTC识别的时候需要提供文本行的位置坐标吗？

**Comment by loralyc** [comment]
@18398639574 代码里面的文件夹就有的啊，你认真检查一下。 识别的时候需要提供文本行的位置坐标，相当于ctpn检测的结果

**Comment by 794767906** [comment]
> @18398639574 train文件夹里有一个txt，如果要改成自己的数据集的话 densenet文件夹里的keys.py也要考虑一下

如何把这个训练的model 拿过来用呢
