### ISSUE TITLE
自然场景下带文本的数据集训练

### ISSUE THREAD

**Issue by Npccc** [YCG09/chinese_ocr#88]
请问您有没有尝试使用自然场景下带文本的数据集来做训练，有的话效果好吗？谢谢

**Comment by YCG09** [comment]
这个要看你是什么用途，我的场景不太需要，中文自然场景样本构造可以参考这个【SynthText_Chinese_version】(https://github.com/JarveeLee/SynthText_Chinese_version)

**Comment by Npccc** [comment]
好的
