### ISSUE TITLE
关于训练集的dictionary 和训练集问题

### ISSUE THREAD

**Issue by xikunlun001** [YCG09/chinese_ocr#9]
我想请教下关于训练集的问题：
下载下来的训练集中的txt文件对图案里每个字符的描述都是一个 int
那是不是有一个dictionary可以查看Int对应的character呢？
如果我想自己加一些训练图片到这个训练集中一起训练，改怎么生成对应的txt呢

感谢~

**Comment by YCG09** [comment]
对，train目录下有个txt，就是你说的dictionary，想增加数据只需要把图片名和图片中每个字在dictionary中的index位置按data_train.txt和data_test.txt中的样本格式追加到相应文件中就可以了

**Comment by YCG09** [comment]
数据是caffe_ocr作者提供的，那两个生成数据的项目需要自己修改下，比如控制宽度，控制高度，控制随机性，控制字数等

**Comment by xikunlun001** [comment]
@YCG09 谢谢~

**Comment by xxllp** [comment]
@YCG09 很感谢作者的项目，想问下这个是否能支持各种证件的ocr识别

**Comment by YCG09** [comment]
@xxllp 可以的，身份证我试过

**Comment by xxllp** [comment]
@YCG09 ，我试了，但是效果还有待提高，这个数据是否直接用身份证的图片训练更好呢。

**Comment by xxllp** [comment]
能提供一些数据生成的方法嘛，很头疼

**Comment by xxllp** [comment]
支持其他证件的识别吗

**Comment by qq542288564** [comment]
@YCG09 怎么固定排版啊，比如有些固定的排版，像营业执照那种有固定格式怎么弄

**Comment by YCG09** [comment]
@qq542288564 根据每个文本框的坐标位置把识别结果还原回去

**Comment by qq542288564** [comment]
@YCG09谢谢您的提示，可以看下您是怎么还原结果的吗，我一行有的中间字间隔有点大，被分为两行了，谢谢哦

**Comment by qq542288564** [comment]
@YCG09哈哈 解决了  谢谢  但是我还有个问题， 如果我想自己训练是应该还要训练你的数据集，不能增量训练把，那么如果增量训练，你的数据集那么大，我自己的数据不是也要很大才有点效果

**Comment by YCG09** [comment]
@qq542288564 恩最好混在一起训练，增量训练你的数据集效果不会好
